##makefile for HuffmanTree project

main: main.o huffman_tree.o
	g++ main.o huffman_tree.o -o main

main.o: main.cc huffman_tree.cpp huffman_tree.h min_heap.h min_heap.template
	g++ -c -Wall main.cc

huffman_tree.o: huffman_tree.cpp huffman_tree.h min_heap.h min_heap.template
	g++ -c -Wall huffman_tree.cpp

clean:
	rm -f *.o *~
